/**
 * kinetic-caption.js
 *
 * Helpers to build ASS (Advanced SubStation Alpha) subtitle files from caption specs.
 *
 * Caption spec expected:
 * [
 *   { start: 1.23, end: 4.56, text: "Hello world", syllables: [ {dur:0.2, text:"Hel"}, ... ] }
 * ]
 *
 * Basic presets: slide-in, fade-up, pop, typewriter, karaoke
 */
import fs from 'fs';

function toAssTime(sec) {
  // ASS times: H:MM:SS.cs (centiseconds)
  const totalCs = Math.round(sec * 100);
  const cs = totalCs % 100;
  let s = Math.floor(totalCs / 100);
  const ss = s % 60; s = Math.floor(s / 60);
  const mm = s % 60; const hh = Math.floor(s / 60);
  return `${hh}:${String(mm).padStart(2,'0')}:${String(ss).padStart(2,'0')}.${String(cs).padStart(2,'0')}`;
}

function escapeASS(text) {
  if (!text) return '';
  // Escape braces and other ASS special chars
  return text.replace(/{/g, "\\{").replace(/}/g, "\\}").replace(/\n/g, "\\N");
}

function buildStyleBlock(style = {}) {
  const fontname = style.font || 'DejaVu Sans';
  const fontsize = style.size || 48;
  const primary = style.color || '&H00FFFFFF'; // white (ASS BGR)
  const bold = style.bold ? '-1' : '0';
  const italic = style.italic ? '-1' : '0';
  const outline = style.outline != null ? style.outline : 2;
  const shadow = style.shadow != null ? style.shadow : 0;
  const alignment = style.alignment || 2; // bottom-center

  // Minimal ASS style line (Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding)
  return `Style: Default,${fontname},${fontsize},${primary},${primary},&H00000000,&H00000000,${bold},${italic},1,${outline},${shadow},${alignment},0,0,10,1`;
}

function buildHeader(styleBlock) {
  return `[Script Info]
; Script generated by ZipZop Kinetic Caption Engine
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
${styleBlock}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
}

function buildDialogueLine(c, preset) {
  const start = toAssTime(c.start);
  const end = toAssTime(c.end);
  const text = escapeASS(c.text || '');

  let overrides = '';

  if (preset === 'slide-in') {
    overrides = '{\\move(640,800,640,620)\\t(0,1000,\\alpha&H00&)}';
  } else if (preset === 'fade-up') {
    overrides = '{\\move(640,660,640,600)\\t(0,800,\\alpha&H00&)}';
  } else if (preset === 'pop') {
    overrides = '{\\t(0,300,\\fscx150\\fscy150)}';
  } else if (preset === 'typewriter') {
    // No per-character reveal unless syllables provided; fallback to fade-in
    overrides = '{\\alpha&HFF&}';
  } else if (preset === 'karaoke') {
    if (Array.isArray(c.syllables) && c.syllables.length > 0) {
      // Build \k tags (duration in centiseconds)
      let kText = '';
      for (const s of c.syllables) {
        const durCs = Math.max(1, Math.round((s.dur || 0.2) * 100));
        kText += `\\k${durCs}${escapeASS(s.text)}`;
      }
      return `Dialogue: 0,${start},${end},Default,,0,0,0,,${kText}`;
    }
  }

  return `Dialogue: 0,${start},${end},Default,,0,0,0,,${overrides}${text}`;
}

export function buildASS(captions = [], style = {}, preset = 'slide-in') {
  const styleBlock = buildStyleBlock(style);
  const header = buildHeader(styleBlock);
  const lines = captions.map((c) => buildDialogueLine(c, preset)).join('\n');
  return header + lines + '\n';
}

export function writeASSFile(assText, outPath) {
  fs.writeFileSync(outPath, assText, 'utf8');
  return outPath;
}

export default { buildASS, writeASSFile };
